### ISSUE TITLE
SPID Quality Assessment

### ISSUE THREAD

**Issue by ruda76** [italia/spid-idp-proxy-shibboleth#4]
Utilizzando lo spid-saml-check sulla configurazione di Shibboleth utilizzando la guida descritta in italia/spid-idp-proxy-shibboleth, non risultano soddisfatti i seguenti controlli:
43. Assertion - Elemento NameID non specificato | FAIL
44. Assertion - Elemento NameID mancante | FAIL
45. Assertion - Attributo Format di NameID non specificato | FAIL
46. Assertion - Attributo Format di NameID mancante | FAIL
47. Assertion - Attributo Format di NameID diverso | FAIL
48. Assertion - Attributo NameQualifier di NameID non specificato | FAIL
49. Assertion - Attributo NameQualifier di NameID mancante | FAIL
70. Assertion - Attributo Format di Issuer non specificato | FAIL
71. Assertion - Attributo Format di Issuer mancante | FAIL
73. Assertion - Elemento Conditions non specificato | FAIL
74. Assertion - Elemento Conditions mancante | FAIL
75. Assertion - Attributo NotBefore di Condition non specificato | FAIL
76. Assertion - Attributo NotBefore di Condition mancante | FAIL
79. Assertion - Attributo NotOnOrAfter di Condition non specificato | FAIL
80. Assertion - Attributo NotOnOrAfter di Condition mancante | FAIL
84. Assertion - Elemento AudienceRestriction di Condition mancante | FAIL

Utilizziamo le ultime versioni di shibboleth SP e IDP, qualcuno può fornire indicazioni in merito?
Grazie

**Comment by peppelinux** [comment]
Ciao, all'interno di questo Proxy puoi implementare la seguente configurazione di SP che sicuramente ti offrirà sollievo :) 
https://github.com/italia/spid-sp-shibboleth/issues

considera di proporre mediante PR l'aggiornamento di questo repository così da usare il repository del SP aggiornato e riumuovere un po di codice legacy, usando questa semplice dipendenza

**Comment by ruda76** [comment]
Ciao,
non ho trovato configurazioni per i punti da me indicati, potresti essere più preciso :)

grazie

**Comment by peppelinux** [comment]
Ops, ho fatto confusione pensando che fosse il repo di ansible shibboleth

@robertogallea ^

**Comment by robertogallea** [comment]
Ciao,
Come avrai visto, la configurazione dell'SP in questo repo rimanda a quella di [italia/spid-sp-shibboleth](https://github.com/italia/spid-sp-shibboleth). Hai usato quella? La configurazione in questione supera i test da te menzionati, quindi mi domando se magari non esegui spid-sp-test con qualche opzione non corretta.

**Comment by ruda76** [comment]
Ciao Roberto, grazie per la risposta.
Si ho utilizzato la configurazione descritta in italia/spid-sp-shibboleth, rispetto a questa però ho dovuto modificare il SessionInitiator per utilizzare il DS (come configurato nelle istruzioni non funzionava):

            <SessionInitiator type="Chaining" id="Login" Location="/Login">

            <SessionInitiator type="SAML2"
                              id="Login"
                              Location="/Login"
                              outgoingBinding="urn:oasis:names:tc:SAML:profiles:SSO:request-init"
                              isPassive="false"
                              acsIndex="0"
                              acsByIndex="true"
                              signing="true">
                <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                                    ID="id_2475824857420t590258902ccccc"
                                    Version="2.0"
                                    IssueInstant="2017-01-01T00:00:00Z"
                                    AttributeConsumingServiceIndex="0"
                                    ForceAuthn="true">
                    <saml:Issuer NameQualifier="https://iam.inarcassa.it/shibboleth"
                                 Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://iam.inarcassa.it/shibboleth</saml:Issuer>
                    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
                </samlp:AuthnRequest>
            </SessionInitiator>

            <SessionInitiator type="SAMLDS"
                              URL="https://iam.inarcassa.it/shibboleth-ds/index.html">
            </SessionInitiator>
            </SessionInitiator

Potrebbe essere questo che crea il problema nella verifica dei punti di cui sopra?
Per le verifiche ho utilizzo l'immagine Docker italia/spid-saml-check, non è altrettando valido?
Per completezza riporto di seguito le versioni dei software utilizzati:

- shibboleth-embedded-ds-1.2.2-3.1.noarch
- shibboleth-3.3.0-1.x86_64
- shibboleth-identity-provider-4.1.6

Sono in una fase di stallo, grazie per qualsiasi informazioni utile a risolvere il problema.

**Comment by ruda76** [comment]
Nessuna idea?

Grazie

**Comment by robertogallea** [comment]
Ciao,
ho guardato meglio la tua problematica. Come indicato sulle issue del repository di shibboleth-sp, il soddisfacimento dei seguenti test non è ancora supportato:

#28
#43
#44
#45
#46
#47
#48
#49
#70
#71
#73
#74
#75
#76
#97
#98

Si tratta tuttavia di test sui quali AGID soprassiede.

Rispetto ai test che a te falliscono, solo i seguenti non fanno parte di quella lista:
79. Assertion - Attributo NotOnOrAfter di Condition non specificato | FAIL
80. Assertion - Attributo NotOnOrAfter di Condition mancante | FAIL
84. Assertion - Elemento AudienceRestriction di Condition mancante | FAIL

#79 e #80 dovrebbero essere correttamente soddisfatti.

Per L'#84 prova a vedere se è legato alle note presenti nel file https://github.com/italia/spid-sp-shibboleth/blob/master/shibboleth/security-policy.xml

**Comment by ruda76** [comment]
Ciao, grazie Roberto.
Effettivamente alcuni controlli sono soprasseduti da AGID, siamo riusciti  a completare la registrazione con successo.

Grazie mille
